cardiology module
BIH-CEI/napkon-cardiology pull request #9
Opened 2021-11-23 15:59 UTC by glichtner

2021-12-03 17:22 UTC, ylboerner requested changes

2021-12-03 17:22 UTC, ylboerner commented on input/fsh/cardiology/p-tricuspid-annular-plane-systolic-excusion.fsh
> +Parent: $gecco-vital-signs-base
This would result in this profile inheriting the vital signs category, which this profile does not belong in. Let's switch this to Observation and find an appropriate category.

2021-12-06 10:30 UTC, glichtner commented on input/fsh/cardiology/cs-napkon-cardiology.fsh
> +* #ecg-bundle-branch-block "ECG: Bundle branch block" // Schenkelblock
It's the parent of the specific branch blocks and is used as the code in instances with "Kein Schenkelblock" or "Keine Informationen verfügbar"

2021-12-06 10:42 UTC, glichtner commented on input/fsh/cardiology/cs-napkon-cardiology.fsh
> +* #ecg-qrs-axis-si-qiii-type "ECG: QRS axis S(I)Q(III) type" // SIQIII-Typ
I had checked these codes and couldn't find 1:1 matches.

For your examples:
* Right axis deviation: +90° to +180°  ([source](https://en.wikipedia.org/wiki/Right_axis_deviation))
* Left axis deviation: -30° to -90°  ([source](https://en.wikipedia.org/wiki/Right_axis_deviation))

From https://flexikon.doccheck.com/de/Lagetyp
* Überdrehter Rechtstyp (üRT): > +120°
* Rechtstyp (RT): +90 bis +120°
* Steiltyp (ST): +60° bis +90°)
* Normal- oder Indifferenztyp (IT): +30° bis +60°
* Linkstyp (LT): -30° bis +30°
* Überdrehter Linkstyp (üLT): < -30°

I therefore suggest leaving the codes as they are.

We could, however, add a component that specifies the exact angle via this LOINC code: https://loinc.org/8632-2/ . What do you think?

2021-12-06 10:43 UTC, glichtner commented on input/fsh/cardiology/vs-ecg-findings.fsh
> +// * $sct#63593006 "Supraventricular premature beats (disorder)" not used // Supraventrikuläre Extrasystolen
removed

2021-12-06 10:43 UTC, glichtner commented on input/fsh/cardiology/vs-ecg-findings.fsh
> +//* $sct#17338001 "Ventricular premature beats (disorder)" -- not used // Ventrikuläre Extrasystolen
removed

2021-12-06 10:52 UTC, glichtner commented on input/fsh/cardiology/p-tricuspid-annular-plane-systolic-excusion.fsh
> +Parent: $gecco-vital-signs-base
done

2021-12-06 10:52 UTC, glichtner commented on input/fsh/cardiology/p-leftventricular-ejection-fraction.fsh
> +Parent: $gecco-vital-signs-base
done

2021-12-06 11:04 UTC, glichtner commented on input/fsh/cardiology/p-ecg-findings.fsh
> +* value[x] only boolean
At least this is the specification for answer possibilities from the medical professionals. "Unknown" is by the way modelled using dataAbsentReason. Additionally, we are at this point not aware of immediate use of the profiles in production. I would therefore leave it as is and only change/discuss it once these profiles should be actively used.

2021-12-10 10:16 UTC, ylboerner commented on input/fsh/cardiology/cs-napkon-cardiology.fsh
> +* #ecg-qrs-axis-si-qiii-type "ECG: QRS axis S(I)Q(III) type" // SIQIII-Typ
That might be slightly overengineered then. Let's leave it as it is and I'll take care of figuring out an improved solution 👍

2021-12-10 10:18 UTC, ylboerner approved these changes

2021-12-10 10:41 UTC, merged